version: '3.8'

services:
  client:
    build:
      target: dev
    volumes:
      - ./client:/user/src/ALX_Project
      - /user/src/ALX_Project/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"

  server:
    build:
      target: dev
    volumes:
      - ./server:/user/src/ALX_Project
      - /user/src/ALX_Project/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
